# Base configs
baseurl: "https://www.denisweiler.de/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Videograph Denis Weiler"
subtitle: "Ich schneide nicht nur, ich erschaffe."
author: "Denis Weiler"
header:
 title: "Videograph"
 subtitle: "Denis Weiler"
footer:
 name: "Willkommen"
 bio: "Ich heiße Denis Weiler, bin 21 Jahre alt, langjähriger Cutter und Videograph aus dem deutschprachigen Raum."
web_design: "AJ"
social_urls:
  youtube: "https://www.youtube.com/MyCoolName"
  twitter: "https://www.twitter.com/mycoolnameyt"
  instagram: "https://www.instagram.com/mycoolnameyt"
